module: StickyEncoding
author: Tony Stone
author_url: http://github.com/tonystone
github_url: http://github.com/stickytools/sticky-encoding
exclude:
  - "Tests/**/*.swift"
  - "Sources/StickyEncoding/BinaryCodingKey.swift"
  - "Sources/StickyEncoding/EncodedType.swift"
  - "Sources/StickyEncoding/KeyedStorageContainer.swift"
  - "Sources/StickyEncoding/NullStorageContainer.swift"
  - "Sources/StickyEncoding/PassthroughReference.swift"
  - "Sources/StickyEncoding/SingleValueContainer.swift"
  - "Sources/StickyEncoding/UnkeyedStorageContainer.swift"

copyright: '© 2019 [Tony Stone](https://github.com/tonystone) under the [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).'

xcodebuild_arguments: [clean,build,-project,StickyEncoding.xcodeproj,-scheme,StickyEncoding-Package]

theme: fullwidth

output: docs

head: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-102615840-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-102615840-6');
  </script>

readme: Sources/Documentation/Index/Index.md
documentation: Sources/Documentation/Sections/*.md
abstract: Sources/Documentation/Abstracts/*.md

custom_categories:
  - name: Encoding & Decoding
    children:
    - BinaryEncoder
    - BinaryDecoder
    - EncodedData
  - name: EncodedData Transformation
    children:
    - Array
    - Data
  - name: Supplemental Information
    children:
    - Binary Format
