#if !canImport(ObjectiveC)
import XCTest

extension BinaryCodingKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryCodingKeyTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithInt", testDebugDescriptionWithInt),
        ("testDescription", testDescription),
        ("testDescriptionWithInt", testDescriptionWithInt),
        ("testFailableInitWithString", testFailableInitWithString),
        ("testInitWithInt", testInitWithInt),
        ("testInitWithString", testInitWithString),
    ]
}

extension BinaryDecoderNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryDecoderNegativeTests = [
        ("testContainerWhenTypeMismatch", testContainerWhenTypeMismatch),
        ("testDecodeWithUserObjectThrowing", testDecodeWithUserObjectThrowing),
        ("testSingleValueContainerWhenTypeMismatch", testSingleValueContainerWhenTypeMismatch),
        ("testUnkeyedContainerWhenTypeMismatch", testUnkeyedContainerWhenTypeMismatch),
    ]
}

extension BinaryEncoderUserObjectNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncoderUserObjectNegativeTests = [
        ("testEncodeWithUserObjectThrowing", testEncodeWithUserObjectThrowing),
    ]
}

extension BinaryEncodingKeyedContainerNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingKeyedContainerNegativeTests = [
        ("testDecodeBoolWhenIncorrectContainerType", testDecodeBoolWhenIncorrectContainerType),
        ("testDecodeBoolWhenKeyNotFound", testDecodeBoolWhenKeyNotFound),
        ("testDecodeBoolWhenTypeMismatch", testDecodeBoolWhenTypeMismatch),
        ("testDecodeBoolWhenValueNotFound", testDecodeBoolWhenValueNotFound),
        ("testDecodeCodableTypeWhenIncorrectContainerType", testDecodeCodableTypeWhenIncorrectContainerType),
        ("testDecodeCodableTypeWhenKeyNotFound", testDecodeCodableTypeWhenKeyNotFound),
        ("testDecodeCodableTypeWhenTypeMismatch", testDecodeCodableTypeWhenTypeMismatch),
        ("testDecodeCodableTypeWhenValueNotFound", testDecodeCodableTypeWhenValueNotFound),
        ("testDecodeDoubleWhenIncorrectContainerType", testDecodeDoubleWhenIncorrectContainerType),
        ("testDecodeDoubleWhenKeyNotFound", testDecodeDoubleWhenKeyNotFound),
        ("testDecodeDoubleWhenTypeMismatch", testDecodeDoubleWhenTypeMismatch),
        ("testDecodeDoubleWhenValueNotFound", testDecodeDoubleWhenValueNotFound),
        ("testDecodeFloatWhenIncorrectContainerType", testDecodeFloatWhenIncorrectContainerType),
        ("testDecodeFloatWhenKeyNotFound", testDecodeFloatWhenKeyNotFound),
        ("testDecodeFloatWhenTypeMismatch", testDecodeFloatWhenTypeMismatch),
        ("testDecodeFloatWhenValueNotFound", testDecodeFloatWhenValueNotFound),
        ("testDecodeInt16WhenIncorrectContainerType", testDecodeInt16WhenIncorrectContainerType),
        ("testDecodeInt16WhenKeyNotFound", testDecodeInt16WhenKeyNotFound),
        ("testDecodeInt16WhenTypeMismatch", testDecodeInt16WhenTypeMismatch),
        ("testDecodeInt16WhenValueNotFound", testDecodeInt16WhenValueNotFound),
        ("testDecodeInt32WhenIncorrectContainerType", testDecodeInt32WhenIncorrectContainerType),
        ("testDecodeInt32WhenKeyNotFound", testDecodeInt32WhenKeyNotFound),
        ("testDecodeInt32WhenTypeMismatch", testDecodeInt32WhenTypeMismatch),
        ("testDecodeInt32WhenValueNotFound", testDecodeInt32WhenValueNotFound),
        ("testDecodeInt64WhenIncorrectContainerType", testDecodeInt64WhenIncorrectContainerType),
        ("testDecodeInt64WhenKeyNotFound", testDecodeInt64WhenKeyNotFound),
        ("testDecodeInt64WhenTypeMismatch", testDecodeInt64WhenTypeMismatch),
        ("testDecodeInt64WhenValueNotFound", testDecodeInt64WhenValueNotFound),
        ("testDecodeInt8WhenIncorrectContainerType", testDecodeInt8WhenIncorrectContainerType),
        ("testDecodeInt8WhenKeyNotFound", testDecodeInt8WhenKeyNotFound),
        ("testDecodeInt8WhenTypeMismatch", testDecodeInt8WhenTypeMismatch),
        ("testDecodeInt8WhenValueNotFound", testDecodeInt8WhenValueNotFound),
        ("testDecodeIntWhenIncorrectContainerType", testDecodeIntWhenIncorrectContainerType),
        ("testDecodeIntWhenKeyNotFound", testDecodeIntWhenKeyNotFound),
        ("testDecodeIntWhenTypeMismatch", testDecodeIntWhenTypeMismatch),
        ("testDecodeIntWhenValueNotFound", testDecodeIntWhenValueNotFound),
        ("testDecodeNilWhenKeyNotFound", testDecodeNilWhenKeyNotFound),
        ("testDecodeStringWhenIncorrectContainerType", testDecodeStringWhenIncorrectContainerType),
        ("testDecodeStringWhenKeyNotFound", testDecodeStringWhenKeyNotFound),
        ("testDecodeStringWhenTypeMismatch", testDecodeStringWhenTypeMismatch),
        ("testDecodeStringWhenValueNotFound", testDecodeStringWhenValueNotFound),
        ("testDecodeUInt16WhenIncorrectContainerType", testDecodeUInt16WhenIncorrectContainerType),
        ("testDecodeUInt16WhenKeyNotFound", testDecodeUInt16WhenKeyNotFound),
        ("testDecodeUInt16WhenTypeMismatch", testDecodeUInt16WhenTypeMismatch),
        ("testDecodeUInt16WhenValueNotFound", testDecodeUInt16WhenValueNotFound),
        ("testDecodeUInt32WhenIncorrectContainerType", testDecodeUInt32WhenIncorrectContainerType),
        ("testDecodeUInt32WhenKeyNotFound", testDecodeUInt32WhenKeyNotFound),
        ("testDecodeUInt32WhenTypeMismatch", testDecodeUInt32WhenTypeMismatch),
        ("testDecodeUInt32WhenValueNotFound", testDecodeUInt32WhenValueNotFound),
        ("testDecodeUInt64WhenIncorrectContainerType", testDecodeUInt64WhenIncorrectContainerType),
        ("testDecodeUInt64WhenKeyNotFound", testDecodeUInt64WhenKeyNotFound),
        ("testDecodeUInt64WhenTypeMismatch", testDecodeUInt64WhenTypeMismatch),
        ("testDecodeUInt64WhenValueNotFound", testDecodeUInt64WhenValueNotFound),
        ("testDecodeUInt8WhenIncorrectContainerType", testDecodeUInt8WhenIncorrectContainerType),
        ("testDecodeUInt8WhenKeyNotFound", testDecodeUInt8WhenKeyNotFound),
        ("testDecodeUInt8WhenTypeMismatch", testDecodeUInt8WhenTypeMismatch),
        ("testDecodeUInt8WhenValueNotFound", testDecodeUInt8WhenValueNotFound),
        ("testDecodeUIntWhenIncorrectContainerType", testDecodeUIntWhenIncorrectContainerType),
        ("testDecodeUIntWhenKeyNotFound", testDecodeUIntWhenKeyNotFound),
        ("testDecodeUIntWhenTypeMismatch", testDecodeUIntWhenTypeMismatch),
        ("testDecodeUIntWhenValueNotFound", testDecodeUIntWhenValueNotFound),
    ]
}

extension BinaryEncodingKeyedContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingKeyedContainerTests = [
        ("testEncodeCallingMultipleKeyedContainers", testEncodeCallingMultipleKeyedContainers),
        ("testEncodeDecodeNilWithKeyedContainer", testEncodeDecodeNilWithKeyedContainer),
        ("testEncodeDecodeOfClassBoolKeyed", testEncodeDecodeOfClassBoolKeyed),
        ("testEncodeDecodeOfClassCodableTypeKeyed", testEncodeDecodeOfClassCodableTypeKeyed),
        ("testEncodeDecodeOfClassDoubleKeyed", testEncodeDecodeOfClassDoubleKeyed),
        ("testEncodeDecodeOfClassFloatKeyed", testEncodeDecodeOfClassFloatKeyed),
        ("testEncodeDecodeOfClassInt16Keyed", testEncodeDecodeOfClassInt16Keyed),
        ("testEncodeDecodeOfClassInt32Keyed", testEncodeDecodeOfClassInt32Keyed),
        ("testEncodeDecodeOfClassInt64Keyed", testEncodeDecodeOfClassInt64Keyed),
        ("testEncodeDecodeOfClassInt8Keyed", testEncodeDecodeOfClassInt8Keyed),
        ("testEncodeDecodeOfClassIntKeyed", testEncodeDecodeOfClassIntKeyed),
        ("testEncodeDecodeOfClassOptionalBoolKeyed", testEncodeDecodeOfClassOptionalBoolKeyed),
        ("testEncodeDecodeOfClassOptionalBoolWithNilKeyed", testEncodeDecodeOfClassOptionalBoolWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalCodableTypeKeyed", testEncodeDecodeOfClassOptionalCodableTypeKeyed),
        ("testEncodeDecodeOfClassOptionalCodableTypeWithNilKeyed", testEncodeDecodeOfClassOptionalCodableTypeWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalDoubleKeyed", testEncodeDecodeOfClassOptionalDoubleKeyed),
        ("testEncodeDecodeOfClassOptionalDoubleWithNilKeyed", testEncodeDecodeOfClassOptionalDoubleWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalFloatKeyed", testEncodeDecodeOfClassOptionalFloatKeyed),
        ("testEncodeDecodeOfClassOptionalFloatWithNilKeyed", testEncodeDecodeOfClassOptionalFloatWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalInt16Keyed", testEncodeDecodeOfClassOptionalInt16Keyed),
        ("testEncodeDecodeOfClassOptionalInt16WithNilKeyed", testEncodeDecodeOfClassOptionalInt16WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalInt32Keyed", testEncodeDecodeOfClassOptionalInt32Keyed),
        ("testEncodeDecodeOfClassOptionalInt32WithNilKeyed", testEncodeDecodeOfClassOptionalInt32WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalInt64Keyed", testEncodeDecodeOfClassOptionalInt64Keyed),
        ("testEncodeDecodeOfClassOptionalInt64WithNilKeyed", testEncodeDecodeOfClassOptionalInt64WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalInt8Keyed", testEncodeDecodeOfClassOptionalInt8Keyed),
        ("testEncodeDecodeOfClassOptionalInt8WithNilKeyed", testEncodeDecodeOfClassOptionalInt8WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalIntKeyed", testEncodeDecodeOfClassOptionalIntKeyed),
        ("testEncodeDecodeOfClassOptionalIntWithNilKeyed", testEncodeDecodeOfClassOptionalIntWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalStringKeyed", testEncodeDecodeOfClassOptionalStringKeyed),
        ("testEncodeDecodeOfClassOptionalStringWithNilKeyed", testEncodeDecodeOfClassOptionalStringWithNilKeyed),
        ("testEncodeDecodeOfClassOptionalUInt16Keyed", testEncodeDecodeOfClassOptionalUInt16Keyed),
        ("testEncodeDecodeOfClassOptionalUInt16WithNilKeyed", testEncodeDecodeOfClassOptionalUInt16WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalUInt32Keyed", testEncodeDecodeOfClassOptionalUInt32Keyed),
        ("testEncodeDecodeOfClassOptionalUInt32WithNilKeyed", testEncodeDecodeOfClassOptionalUInt32WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalUInt64Keyed", testEncodeDecodeOfClassOptionalUInt64Keyed),
        ("testEncodeDecodeOfClassOptionalUInt64WithNilKeyed", testEncodeDecodeOfClassOptionalUInt64WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalUInt8Keyed", testEncodeDecodeOfClassOptionalUInt8Keyed),
        ("testEncodeDecodeOfClassOptionalUInt8WithNilKeyed", testEncodeDecodeOfClassOptionalUInt8WithNilKeyed),
        ("testEncodeDecodeOfClassOptionalUIntKeyed", testEncodeDecodeOfClassOptionalUIntKeyed),
        ("testEncodeDecodeOfClassOptionalUIntWithNilKeyed", testEncodeDecodeOfClassOptionalUIntWithNilKeyed),
        ("testEncodeDecodeOfClassStringKeyed", testEncodeDecodeOfClassStringKeyed),
        ("testEncodeDecodeOfClassUInt16Keyed", testEncodeDecodeOfClassUInt16Keyed),
        ("testEncodeDecodeOfClassUInt32Keyed", testEncodeDecodeOfClassUInt32Keyed),
        ("testEncodeDecodeOfClassUInt64Keyed", testEncodeDecodeOfClassUInt64Keyed),
        ("testEncodeDecodeOfClassUInt8Keyed", testEncodeDecodeOfClassUInt8Keyed),
        ("testEncodeDecodeOfClassUIntKeyed", testEncodeDecodeOfClassUIntKeyed),
        ("testEncodeDecodeOfStructBoolKeyed", testEncodeDecodeOfStructBoolKeyed),
        ("testEncodeDecodeOfStructCodableTypeKeyed", testEncodeDecodeOfStructCodableTypeKeyed),
        ("testEncodeDecodeOfStructDoubleKeyed", testEncodeDecodeOfStructDoubleKeyed),
        ("testEncodeDecodeOfStructFloatKeyed", testEncodeDecodeOfStructFloatKeyed),
        ("testEncodeDecodeOfStructInt16Keyed", testEncodeDecodeOfStructInt16Keyed),
        ("testEncodeDecodeOfStructInt32Keyed", testEncodeDecodeOfStructInt32Keyed),
        ("testEncodeDecodeOfStructInt64Keyed", testEncodeDecodeOfStructInt64Keyed),
        ("testEncodeDecodeOfStructInt8Keyed", testEncodeDecodeOfStructInt8Keyed),
        ("testEncodeDecodeOfStructIntKeyed", testEncodeDecodeOfStructIntKeyed),
        ("testEncodeDecodeOfStructOptionalBoolKeyed", testEncodeDecodeOfStructOptionalBoolKeyed),
        ("testEncodeDecodeOfStructOptionalBoolWithNilKeyed", testEncodeDecodeOfStructOptionalBoolWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalCodableTypeKeyed", testEncodeDecodeOfStructOptionalCodableTypeKeyed),
        ("testEncodeDecodeOfStructOptionalCodableTypeWithNilKeyed", testEncodeDecodeOfStructOptionalCodableTypeWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalDoubleKeyed", testEncodeDecodeOfStructOptionalDoubleKeyed),
        ("testEncodeDecodeOfStructOptionalDoubleWithNilKeyed", testEncodeDecodeOfStructOptionalDoubleWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalFloatKeyed", testEncodeDecodeOfStructOptionalFloatKeyed),
        ("testEncodeDecodeOfStructOptionalFloatWithNilKeyed", testEncodeDecodeOfStructOptionalFloatWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalInt16Keyed", testEncodeDecodeOfStructOptionalInt16Keyed),
        ("testEncodeDecodeOfStructOptionalInt16WithNilKeyed", testEncodeDecodeOfStructOptionalInt16WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalInt32Keyed", testEncodeDecodeOfStructOptionalInt32Keyed),
        ("testEncodeDecodeOfStructOptionalInt32WithNilKeyed", testEncodeDecodeOfStructOptionalInt32WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalInt64Keyed", testEncodeDecodeOfStructOptionalInt64Keyed),
        ("testEncodeDecodeOfStructOptionalInt64WithNilKeyed", testEncodeDecodeOfStructOptionalInt64WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalInt8Keyed", testEncodeDecodeOfStructOptionalInt8Keyed),
        ("testEncodeDecodeOfStructOptionalInt8WithNilKeyed", testEncodeDecodeOfStructOptionalInt8WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalIntKeyed", testEncodeDecodeOfStructOptionalIntKeyed),
        ("testEncodeDecodeOfStructOptionalIntWithNilKeyed", testEncodeDecodeOfStructOptionalIntWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalStringKeyed", testEncodeDecodeOfStructOptionalStringKeyed),
        ("testEncodeDecodeOfStructOptionalStringWithNilKeyed", testEncodeDecodeOfStructOptionalStringWithNilKeyed),
        ("testEncodeDecodeOfStructOptionalUInt16Keyed", testEncodeDecodeOfStructOptionalUInt16Keyed),
        ("testEncodeDecodeOfStructOptionalUInt16WithNilKeyed", testEncodeDecodeOfStructOptionalUInt16WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalUInt32Keyed", testEncodeDecodeOfStructOptionalUInt32Keyed),
        ("testEncodeDecodeOfStructOptionalUInt32WithNilKeyed", testEncodeDecodeOfStructOptionalUInt32WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalUInt64Keyed", testEncodeDecodeOfStructOptionalUInt64Keyed),
        ("testEncodeDecodeOfStructOptionalUInt64WithNilKeyed", testEncodeDecodeOfStructOptionalUInt64WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalUInt8Keyed", testEncodeDecodeOfStructOptionalUInt8Keyed),
        ("testEncodeDecodeOfStructOptionalUInt8WithNilKeyed", testEncodeDecodeOfStructOptionalUInt8WithNilKeyed),
        ("testEncodeDecodeOfStructOptionalUIntKeyed", testEncodeDecodeOfStructOptionalUIntKeyed),
        ("testEncodeDecodeOfStructOptionalUIntWithNilKeyed", testEncodeDecodeOfStructOptionalUIntWithNilKeyed),
        ("testEncodeDecodeOfStructStringKeyed", testEncodeDecodeOfStructStringKeyed),
        ("testEncodeDecodeOfStructUInt16Keyed", testEncodeDecodeOfStructUInt16Keyed),
        ("testEncodeDecodeOfStructUInt32Keyed", testEncodeDecodeOfStructUInt32Keyed),
        ("testEncodeDecodeOfStructUInt64Keyed", testEncodeDecodeOfStructUInt64Keyed),
        ("testEncodeDecodeOfStructUInt8Keyed", testEncodeDecodeOfStructUInt8Keyed),
        ("testEncodeDecodeOfStructUIntKeyed", testEncodeDecodeOfStructUIntKeyed),
        ("testEncodeDecodeWithKeyedAndNestedKeyedContainers", testEncodeDecodeWithKeyedAndNestedKeyedContainers),
        ("testEncodeDecodeWithSuperEncoderDecoderKeyedContainer", testEncodeDecodeWithSuperEncoderDecoderKeyedContainer),
        ("testEncodeDecodeWithSuperEncoderDecoderUnkeyedContainer", testEncodeDecodeWithSuperEncoderDecoderUnkeyedContainer),
        ("testEncodeWithKeyedAndNestedUnkeyedContainers", testEncodeWithKeyedAndNestedUnkeyedContainers),
    ]
}

extension BinaryEncodingSingleValueContainerNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingSingleValueContainerNegativeTests = [
        ("testDecodeTypeMismatchOfBool", testDecodeTypeMismatchOfBool),
        ("testDecodeTypeMismatchOfBoolWhenIncorrectContainerType", testDecodeTypeMismatchOfBoolWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfCodableType", testDecodeTypeMismatchOfCodableType),
        ("testDecodeTypeMismatchOfCodableTypeWhenIncorrectContainerType", testDecodeTypeMismatchOfCodableTypeWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfDouble", testDecodeTypeMismatchOfDouble),
        ("testDecodeTypeMismatchOfDoubleWhenIncorrectContainerType", testDecodeTypeMismatchOfDoubleWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfFloat", testDecodeTypeMismatchOfFloat),
        ("testDecodeTypeMismatchOfFloatWhenIncorrectContainerType", testDecodeTypeMismatchOfFloatWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfInt", testDecodeTypeMismatchOfInt),
        ("testDecodeTypeMismatchOfInt16", testDecodeTypeMismatchOfInt16),
        ("testDecodeTypeMismatchOfInt16WhenIncorrectContainerType", testDecodeTypeMismatchOfInt16WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfInt32", testDecodeTypeMismatchOfInt32),
        ("testDecodeTypeMismatchOfInt32WhenIncorrectContainerType", testDecodeTypeMismatchOfInt32WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfInt64", testDecodeTypeMismatchOfInt64),
        ("testDecodeTypeMismatchOfInt64WhenIncorrectContainerType", testDecodeTypeMismatchOfInt64WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfInt8", testDecodeTypeMismatchOfInt8),
        ("testDecodeTypeMismatchOfInt8WhenIncorrectContainerType", testDecodeTypeMismatchOfInt8WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfIntWhenIncorrectContainerType", testDecodeTypeMismatchOfIntWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfString", testDecodeTypeMismatchOfString),
        ("testDecodeTypeMismatchOfStringWhenIncorrectContainerType", testDecodeTypeMismatchOfStringWhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfUInt", testDecodeTypeMismatchOfUInt),
        ("testDecodeTypeMismatchOfUInt16", testDecodeTypeMismatchOfUInt16),
        ("testDecodeTypeMismatchOfUInt16WhenIncorrectContainerType", testDecodeTypeMismatchOfUInt16WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfUInt32", testDecodeTypeMismatchOfUInt32),
        ("testDecodeTypeMismatchOfUInt32WhenIncorrectContainerType", testDecodeTypeMismatchOfUInt32WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfUInt64", testDecodeTypeMismatchOfUInt64),
        ("testDecodeTypeMismatchOfUInt64WhenIncorrectContainerType", testDecodeTypeMismatchOfUInt64WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfUInt8", testDecodeTypeMismatchOfUInt8),
        ("testDecodeTypeMismatchOfUInt8WhenIncorrectContainerType", testDecodeTypeMismatchOfUInt8WhenIncorrectContainerType),
        ("testDecodeTypeMismatchOfUIntWhenIncorrectContainerType", testDecodeTypeMismatchOfUIntWhenIncorrectContainerType),
        ("testDecodeValueNotFoundOfBool", testDecodeValueNotFoundOfBool),
        ("testDecodeValueNotFoundOfCodableType", testDecodeValueNotFoundOfCodableType),
        ("testDecodeValueNotFoundOfDouble", testDecodeValueNotFoundOfDouble),
        ("testDecodeValueNotFoundOfFloat", testDecodeValueNotFoundOfFloat),
        ("testDecodeValueNotFoundOfInt", testDecodeValueNotFoundOfInt),
        ("testDecodeValueNotFoundOfInt16", testDecodeValueNotFoundOfInt16),
        ("testDecodeValueNotFoundOfInt32", testDecodeValueNotFoundOfInt32),
        ("testDecodeValueNotFoundOfInt64", testDecodeValueNotFoundOfInt64),
        ("testDecodeValueNotFoundOfInt8", testDecodeValueNotFoundOfInt8),
        ("testDecodeValueNotFoundOfString", testDecodeValueNotFoundOfString),
        ("testDecodeValueNotFoundOfUInt", testDecodeValueNotFoundOfUInt),
        ("testDecodeValueNotFoundOfUInt16", testDecodeValueNotFoundOfUInt16),
        ("testDecodeValueNotFoundOfUInt32", testDecodeValueNotFoundOfUInt32),
        ("testDecodeValueNotFoundOfUInt64", testDecodeValueNotFoundOfUInt64),
        ("testDecodeValueNotFoundOfUInt8", testDecodeValueNotFoundOfUInt8),
    ]
}

extension BinaryEncodingSingleValueContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingSingleValueContainerTests = [
        ("testEncodingDecodeOfBool", testEncodingDecodeOfBool),
        ("testEncodingDecodeOfCodableType", testEncodingDecodeOfCodableType),
        ("testEncodingDecodeOfDouble", testEncodingDecodeOfDouble),
        ("testEncodingDecodeOfFloat", testEncodingDecodeOfFloat),
        ("testEncodingDecodeOfInt", testEncodingDecodeOfInt),
        ("testEncodingDecodeOfInt16", testEncodingDecodeOfInt16),
        ("testEncodingDecodeOfInt16Max", testEncodingDecodeOfInt16Max),
        ("testEncodingDecodeOfInt16Min", testEncodingDecodeOfInt16Min),
        ("testEncodingDecodeOfInt16Zero", testEncodingDecodeOfInt16Zero),
        ("testEncodingDecodeOfInt32", testEncodingDecodeOfInt32),
        ("testEncodingDecodeOfInt32Max", testEncodingDecodeOfInt32Max),
        ("testEncodingDecodeOfInt32Min", testEncodingDecodeOfInt32Min),
        ("testEncodingDecodeOfInt32Zero", testEncodingDecodeOfInt32Zero),
        ("testEncodingDecodeOfInt64", testEncodingDecodeOfInt64),
        ("testEncodingDecodeOfInt64Max", testEncodingDecodeOfInt64Max),
        ("testEncodingDecodeOfInt64Min", testEncodingDecodeOfInt64Min),
        ("testEncodingDecodeOfInt64Zero", testEncodingDecodeOfInt64Zero),
        ("testEncodingDecodeOfInt8", testEncodingDecodeOfInt8),
        ("testEncodingDecodeOfInt8Max", testEncodingDecodeOfInt8Max),
        ("testEncodingDecodeOfInt8Min", testEncodingDecodeOfInt8Min),
        ("testEncodingDecodeOfInt8Zero", testEncodingDecodeOfInt8Zero),
        ("testEncodingDecodeOfIntMax", testEncodingDecodeOfIntMax),
        ("testEncodingDecodeOfIntMin", testEncodingDecodeOfIntMin),
        ("testEncodingDecodeOfIntZero", testEncodingDecodeOfIntZero),
        ("testEncodingDecodeOfOptionalBool", testEncodingDecodeOfOptionalBool),
        ("testEncodingDecodeOfOptionalBoolNil", testEncodingDecodeOfOptionalBoolNil),
        ("testEncodingDecodeOfOptionalCodableType", testEncodingDecodeOfOptionalCodableType),
        ("testEncodingDecodeOfOptionalCodableTypeNil", testEncodingDecodeOfOptionalCodableTypeNil),
        ("testEncodingDecodeOfOptionalDouble", testEncodingDecodeOfOptionalDouble),
        ("testEncodingDecodeOfOptionalDoubleNil", testEncodingDecodeOfOptionalDoubleNil),
        ("testEncodingDecodeOfOptionalFloat", testEncodingDecodeOfOptionalFloat),
        ("testEncodingDecodeOfOptionalFloatNil", testEncodingDecodeOfOptionalFloatNil),
        ("testEncodingDecodeOfOptionalInt", testEncodingDecodeOfOptionalInt),
        ("testEncodingDecodeOfOptionalInt16", testEncodingDecodeOfOptionalInt16),
        ("testEncodingDecodeOfOptionalInt16Max", testEncodingDecodeOfOptionalInt16Max),
        ("testEncodingDecodeOfOptionalInt16Min", testEncodingDecodeOfOptionalInt16Min),
        ("testEncodingDecodeOfOptionalInt16Nil", testEncodingDecodeOfOptionalInt16Nil),
        ("testEncodingDecodeOfOptionalInt16Zero", testEncodingDecodeOfOptionalInt16Zero),
        ("testEncodingDecodeOfOptionalInt32", testEncodingDecodeOfOptionalInt32),
        ("testEncodingDecodeOfOptionalInt32Max", testEncodingDecodeOfOptionalInt32Max),
        ("testEncodingDecodeOfOptionalInt32Min", testEncodingDecodeOfOptionalInt32Min),
        ("testEncodingDecodeOfOptionalInt32Nil", testEncodingDecodeOfOptionalInt32Nil),
        ("testEncodingDecodeOfOptionalInt32Zero", testEncodingDecodeOfOptionalInt32Zero),
        ("testEncodingDecodeOfOptionalInt64", testEncodingDecodeOfOptionalInt64),
        ("testEncodingDecodeOfOptionalInt64Max", testEncodingDecodeOfOptionalInt64Max),
        ("testEncodingDecodeOfOptionalInt64Min", testEncodingDecodeOfOptionalInt64Min),
        ("testEncodingDecodeOfOptionalInt64Nil", testEncodingDecodeOfOptionalInt64Nil),
        ("testEncodingDecodeOfOptionalInt64Zero", testEncodingDecodeOfOptionalInt64Zero),
        ("testEncodingDecodeOfOptionalInt8", testEncodingDecodeOfOptionalInt8),
        ("testEncodingDecodeOfOptionalInt8Max", testEncodingDecodeOfOptionalInt8Max),
        ("testEncodingDecodeOfOptionalInt8Min", testEncodingDecodeOfOptionalInt8Min),
        ("testEncodingDecodeOfOptionalInt8Nil", testEncodingDecodeOfOptionalInt8Nil),
        ("testEncodingDecodeOfOptionalInt8Zero", testEncodingDecodeOfOptionalInt8Zero),
        ("testEncodingDecodeOfOptionalIntMax", testEncodingDecodeOfOptionalIntMax),
        ("testEncodingDecodeOfOptionalIntMin", testEncodingDecodeOfOptionalIntMin),
        ("testEncodingDecodeOfOptionalIntNil", testEncodingDecodeOfOptionalIntNil),
        ("testEncodingDecodeOfOptionalIntZero", testEncodingDecodeOfOptionalIntZero),
        ("testEncodingDecodeOfOptionalString", testEncodingDecodeOfOptionalString),
        ("testEncodingDecodeOfOptionalStringNil", testEncodingDecodeOfOptionalStringNil),
        ("testEncodingDecodeOfOptionalUInt", testEncodingDecodeOfOptionalUInt),
        ("testEncodingDecodeOfOptionalUInt16", testEncodingDecodeOfOptionalUInt16),
        ("testEncodingDecodeOfOptionalUInt16Max", testEncodingDecodeOfOptionalUInt16Max),
        ("testEncodingDecodeOfOptionalUInt16Min", testEncodingDecodeOfOptionalUInt16Min),
        ("testEncodingDecodeOfOptionalUInt16Nil", testEncodingDecodeOfOptionalUInt16Nil),
        ("testEncodingDecodeOfOptionalUInt16Zero", testEncodingDecodeOfOptionalUInt16Zero),
        ("testEncodingDecodeOfOptionalUInt32", testEncodingDecodeOfOptionalUInt32),
        ("testEncodingDecodeOfOptionalUInt32Max", testEncodingDecodeOfOptionalUInt32Max),
        ("testEncodingDecodeOfOptionalUInt32Min", testEncodingDecodeOfOptionalUInt32Min),
        ("testEncodingDecodeOfOptionalUInt32Nil", testEncodingDecodeOfOptionalUInt32Nil),
        ("testEncodingDecodeOfOptionalUInt32Zero", testEncodingDecodeOfOptionalUInt32Zero),
        ("testEncodingDecodeOfOptionalUInt64", testEncodingDecodeOfOptionalUInt64),
        ("testEncodingDecodeOfOptionalUInt64Max", testEncodingDecodeOfOptionalUInt64Max),
        ("testEncodingDecodeOfOptionalUInt64Min", testEncodingDecodeOfOptionalUInt64Min),
        ("testEncodingDecodeOfOptionalUInt64Nil", testEncodingDecodeOfOptionalUInt64Nil),
        ("testEncodingDecodeOfOptionalUInt64Zero", testEncodingDecodeOfOptionalUInt64Zero),
        ("testEncodingDecodeOfOptionalUInt8", testEncodingDecodeOfOptionalUInt8),
        ("testEncodingDecodeOfOptionalUInt8Max", testEncodingDecodeOfOptionalUInt8Max),
        ("testEncodingDecodeOfOptionalUInt8Min", testEncodingDecodeOfOptionalUInt8Min),
        ("testEncodingDecodeOfOptionalUInt8Nil", testEncodingDecodeOfOptionalUInt8Nil),
        ("testEncodingDecodeOfOptionalUInt8Zero", testEncodingDecodeOfOptionalUInt8Zero),
        ("testEncodingDecodeOfOptionalUIntMax", testEncodingDecodeOfOptionalUIntMax),
        ("testEncodingDecodeOfOptionalUIntMin", testEncodingDecodeOfOptionalUIntMin),
        ("testEncodingDecodeOfOptionalUIntNil", testEncodingDecodeOfOptionalUIntNil),
        ("testEncodingDecodeOfOptionalUIntZero", testEncodingDecodeOfOptionalUIntZero),
        ("testEncodingDecodeOfString", testEncodingDecodeOfString),
        ("testEncodingDecodeOfUInt", testEncodingDecodeOfUInt),
        ("testEncodingDecodeOfUInt16", testEncodingDecodeOfUInt16),
        ("testEncodingDecodeOfUInt16Max", testEncodingDecodeOfUInt16Max),
        ("testEncodingDecodeOfUInt16Min", testEncodingDecodeOfUInt16Min),
        ("testEncodingDecodeOfUInt16Zero", testEncodingDecodeOfUInt16Zero),
        ("testEncodingDecodeOfUInt32", testEncodingDecodeOfUInt32),
        ("testEncodingDecodeOfUInt32Max", testEncodingDecodeOfUInt32Max),
        ("testEncodingDecodeOfUInt32Min", testEncodingDecodeOfUInt32Min),
        ("testEncodingDecodeOfUInt32Zero", testEncodingDecodeOfUInt32Zero),
        ("testEncodingDecodeOfUInt64", testEncodingDecodeOfUInt64),
        ("testEncodingDecodeOfUInt64Max", testEncodingDecodeOfUInt64Max),
        ("testEncodingDecodeOfUInt64Min", testEncodingDecodeOfUInt64Min),
        ("testEncodingDecodeOfUInt64Zero", testEncodingDecodeOfUInt64Zero),
        ("testEncodingDecodeOfUInt8", testEncodingDecodeOfUInt8),
        ("testEncodingDecodeOfUInt8Max", testEncodingDecodeOfUInt8Max),
        ("testEncodingDecodeOfUInt8Min", testEncodingDecodeOfUInt8Min),
        ("testEncodingDecodeOfUInt8Zero", testEncodingDecodeOfUInt8Zero),
        ("testEncodingDecodeOfUIntMax", testEncodingDecodeOfUIntMax),
        ("testEncodingDecodeOfUIntMin", testEncodingDecodeOfUIntMin),
        ("testEncodingDecodeOfUIntZero", testEncodingDecodeOfUIntZero),
    ]
}

extension BinaryEncodingStructuredTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingStructuredTypeTests = [
        ("testEncodingDecodeOfArrayOfInt", testEncodingDecodeOfArrayOfInt),
        ("testEncodingDecodeOfBasicClass", testEncodingDecodeOfBasicClass),
        ("testEncodingDecodeOfBasicStruct", testEncodingDecodeOfBasicStruct),
        ("testEncodingDecodeOfComplexClass", testEncodingDecodeOfComplexClass),
        ("testEncodingDecodeOfComplexStruct", testEncodingDecodeOfComplexStruct),
        ("testEncodingDecodeOfComplexSubclassClass", testEncodingDecodeOfComplexSubclassClass),
        ("testEncodingDecodeOfDictionaryOfEnum", testEncodingDecodeOfDictionaryOfEnum),
        ("testEncodingDecodeOfDictionaryOfEnumKeys", testEncodingDecodeOfDictionaryOfEnumKeys),
        ("testEncodingDecodeOfDictionaryOfEnumValues", testEncodingDecodeOfDictionaryOfEnumValues),
    ]
}

extension BinaryEncodingUnkeyedContainerNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingUnkeyedContainerNegativeTests = [
        ("testDecodeBoolTypeMismatchWhenValueNotConvertable", testDecodeBoolTypeMismatchWhenValueNotConvertable),
        ("testDecodeBoolTypeMismatchWhenValueNotCorrectContainerType", testDecodeBoolTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeBoolValueNotFoundWhenContainerIsNil", testDecodeBoolValueNotFoundWhenContainerIsNil),
        ("testDecodeBoolValueNotFoundWhenNoMoreValues", testDecodeBoolValueNotFoundWhenNoMoreValues),
        ("testDecodeBoolValueNotFoundWhenValueIsNil", testDecodeBoolValueNotFoundWhenValueIsNil),
        ("testDecodeCodableTypeTypeMismatchWhenValueNotConvertable", testDecodeCodableTypeTypeMismatchWhenValueNotConvertable),
        ("testDecodeCodableTypeTypeMismatchWhenValueNotCorrectContainerType", testDecodeCodableTypeTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeCodableTypeValueNotFoundWhenContainerIsNil", testDecodeCodableTypeValueNotFoundWhenContainerIsNil),
        ("testDecodeCodableTypeValueNotFoundWhenNoMoreValues", testDecodeCodableTypeValueNotFoundWhenNoMoreValues),
        ("testDecodeCodableTypeValueNotFoundWhenValueIsNil", testDecodeCodableTypeValueNotFoundWhenValueIsNil),
        ("testDecodeDoubleTypeMismatchWhenValueNotConvertable", testDecodeDoubleTypeMismatchWhenValueNotConvertable),
        ("testDecodeDoubleTypeMismatchWhenValueNotCorrectContainerType", testDecodeDoubleTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeDoubleValueNotFoundWhenContainerIsNil", testDecodeDoubleValueNotFoundWhenContainerIsNil),
        ("testDecodeDoubleValueNotFoundWhenNoMoreValues", testDecodeDoubleValueNotFoundWhenNoMoreValues),
        ("testDecodeDoubleValueNotFoundWhenValueIsNil", testDecodeDoubleValueNotFoundWhenValueIsNil),
        ("testDecodeFloatTypeMismatchWhenValueNotConvertable", testDecodeFloatTypeMismatchWhenValueNotConvertable),
        ("testDecodeFloatTypeMismatchWhenValueNotCorrectContainerType", testDecodeFloatTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeFloatValueNotFoundWhenContainerIsNil", testDecodeFloatValueNotFoundWhenContainerIsNil),
        ("testDecodeFloatValueNotFoundWhenNoMoreValues", testDecodeFloatValueNotFoundWhenNoMoreValues),
        ("testDecodeFloatValueNotFoundWhenValueIsNil", testDecodeFloatValueNotFoundWhenValueIsNil),
        ("testDecodeInt16TypeMismatchWhenValueNotConvertable", testDecodeInt16TypeMismatchWhenValueNotConvertable),
        ("testDecodeInt16TypeMismatchWhenValueNotCorrectContainerType", testDecodeInt16TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeInt16ValueNotFoundWhenContainerIsNil", testDecodeInt16ValueNotFoundWhenContainerIsNil),
        ("testDecodeInt16ValueNotFoundWhenNoMoreValues", testDecodeInt16ValueNotFoundWhenNoMoreValues),
        ("testDecodeInt16ValueNotFoundWhenValueIsNil", testDecodeInt16ValueNotFoundWhenValueIsNil),
        ("testDecodeInt32TypeMismatchWhenValueNotConvertable", testDecodeInt32TypeMismatchWhenValueNotConvertable),
        ("testDecodeInt32TypeMismatchWhenValueNotCorrectContainerType", testDecodeInt32TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeInt32ValueNotFoundWhenContainerIsNil", testDecodeInt32ValueNotFoundWhenContainerIsNil),
        ("testDecodeInt32ValueNotFoundWhenNoMoreValues", testDecodeInt32ValueNotFoundWhenNoMoreValues),
        ("testDecodeInt32ValueNotFoundWhenValueIsNil", testDecodeInt32ValueNotFoundWhenValueIsNil),
        ("testDecodeInt64TypeMismatchWhenValueNotConvertable", testDecodeInt64TypeMismatchWhenValueNotConvertable),
        ("testDecodeInt64TypeMismatchWhenValueNotCorrectContainerType", testDecodeInt64TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeInt64ValueNotFoundWhenContainerIsNil", testDecodeInt64ValueNotFoundWhenContainerIsNil),
        ("testDecodeInt64ValueNotFoundWhenNoMoreValues", testDecodeInt64ValueNotFoundWhenNoMoreValues),
        ("testDecodeInt64ValueNotFoundWhenValueIsNil", testDecodeInt64ValueNotFoundWhenValueIsNil),
        ("testDecodeInt8TypeMismatchWhenValueNotConvertable", testDecodeInt8TypeMismatchWhenValueNotConvertable),
        ("testDecodeInt8TypeMismatchWhenValueNotCorrectContainerType", testDecodeInt8TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeInt8ValueNotFoundWhenContainerIsNil", testDecodeInt8ValueNotFoundWhenContainerIsNil),
        ("testDecodeInt8ValueNotFoundWhenNoMoreValues", testDecodeInt8ValueNotFoundWhenNoMoreValues),
        ("testDecodeInt8ValueNotFoundWhenValueIsNil", testDecodeInt8ValueNotFoundWhenValueIsNil),
        ("testDecodeIntTypeMismatchWhenValueNotConvertable", testDecodeIntTypeMismatchWhenValueNotConvertable),
        ("testDecodeIntTypeMismatchWhenValueNotCorrectContainerType", testDecodeIntTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeIntValueNotFoundWhenContainerIsNil", testDecodeIntValueNotFoundWhenContainerIsNil),
        ("testDecodeIntValueNotFoundWhenNoMoreValues", testDecodeIntValueNotFoundWhenNoMoreValues),
        ("testDecodeIntValueNotFoundWhenValueIsNil", testDecodeIntValueNotFoundWhenValueIsNil),
        ("testDecodeStringTypeMismatchWhenValueNotConvertable", testDecodeStringTypeMismatchWhenValueNotConvertable),
        ("testDecodeStringTypeMismatchWhenValueNotCorrectContainerType", testDecodeStringTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeStringValueNotFoundWhenContainerIsNil", testDecodeStringValueNotFoundWhenContainerIsNil),
        ("testDecodeStringValueNotFoundWhenNoMoreValues", testDecodeStringValueNotFoundWhenNoMoreValues),
        ("testDecodeStringValueNotFoundWhenValueIsNil", testDecodeStringValueNotFoundWhenValueIsNil),
        ("testDecodeUInt16TypeMismatchWhenValueNotConvertable", testDecodeUInt16TypeMismatchWhenValueNotConvertable),
        ("testDecodeUInt16TypeMismatchWhenValueNotCorrectContainerType", testDecodeUInt16TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeUInt16ValueNotFoundWhenContainerIsNil", testDecodeUInt16ValueNotFoundWhenContainerIsNil),
        ("testDecodeUInt16ValueNotFoundWhenNoMoreValues", testDecodeUInt16ValueNotFoundWhenNoMoreValues),
        ("testDecodeUInt16ValueNotFoundWhenValueIsNil", testDecodeUInt16ValueNotFoundWhenValueIsNil),
        ("testDecodeUInt32TypeMismatchWhenValueNotConvertable", testDecodeUInt32TypeMismatchWhenValueNotConvertable),
        ("testDecodeUInt32TypeMismatchWhenValueNotCorrectContainerType", testDecodeUInt32TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeUInt32ValueNotFoundWhenContainerIsNil", testDecodeUInt32ValueNotFoundWhenContainerIsNil),
        ("testDecodeUInt32ValueNotFoundWhenNoMoreValues", testDecodeUInt32ValueNotFoundWhenNoMoreValues),
        ("testDecodeUInt32ValueNotFoundWhenValueIsNil", testDecodeUInt32ValueNotFoundWhenValueIsNil),
        ("testDecodeUInt64TypeMismatchWhenValueNotConvertable", testDecodeUInt64TypeMismatchWhenValueNotConvertable),
        ("testDecodeUInt64TypeMismatchWhenValueNotCorrectContainerType", testDecodeUInt64TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeUInt64ValueNotFoundWhenContainerIsNil", testDecodeUInt64ValueNotFoundWhenContainerIsNil),
        ("testDecodeUInt64ValueNotFoundWhenNoMoreValues", testDecodeUInt64ValueNotFoundWhenNoMoreValues),
        ("testDecodeUInt64ValueNotFoundWhenValueIsNil", testDecodeUInt64ValueNotFoundWhenValueIsNil),
        ("testDecodeUInt8TypeMismatchWhenValueNotConvertable", testDecodeUInt8TypeMismatchWhenValueNotConvertable),
        ("testDecodeUInt8TypeMismatchWhenValueNotCorrectContainerType", testDecodeUInt8TypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeUInt8ValueNotFoundWhenContainerIsNil", testDecodeUInt8ValueNotFoundWhenContainerIsNil),
        ("testDecodeUInt8ValueNotFoundWhenNoMoreValues", testDecodeUInt8ValueNotFoundWhenNoMoreValues),
        ("testDecodeUInt8ValueNotFoundWhenValueIsNil", testDecodeUInt8ValueNotFoundWhenValueIsNil),
        ("testDecodeUIntTypeMismatchWhenValueNotConvertable", testDecodeUIntTypeMismatchWhenValueNotConvertable),
        ("testDecodeUIntTypeMismatchWhenValueNotCorrectContainerType", testDecodeUIntTypeMismatchWhenValueNotCorrectContainerType),
        ("testDecodeUIntValueNotFoundWhenContainerIsNil", testDecodeUIntValueNotFoundWhenContainerIsNil),
        ("testDecodeUIntValueNotFoundWhenNoMoreValues", testDecodeUIntValueNotFoundWhenNoMoreValues),
        ("testDecodeUIntValueNotFoundWhenValueIsNil", testDecodeUIntValueNotFoundWhenValueIsNil),
    ]
}

extension BinaryEncodingUnkeyedContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingUnkeyedContainerTests = [
        ("testEncodeCallingMultipleUnkeyedContainers", testEncodeCallingMultipleUnkeyedContainers),
        ("testEncodeDecodeOfClassBoolUnkeyed", testEncodeDecodeOfClassBoolUnkeyed),
        ("testEncodeDecodeOfClassCodableTypeUnkeyed", testEncodeDecodeOfClassCodableTypeUnkeyed),
        ("testEncodeDecodeOfClassDoubleUnkeyed", testEncodeDecodeOfClassDoubleUnkeyed),
        ("testEncodeDecodeOfClassFloatUnkeyed", testEncodeDecodeOfClassFloatUnkeyed),
        ("testEncodeDecodeOfClassInt16Unkeyed", testEncodeDecodeOfClassInt16Unkeyed),
        ("testEncodeDecodeOfClassInt32Unkeyed", testEncodeDecodeOfClassInt32Unkeyed),
        ("testEncodeDecodeOfClassInt64Unkeyed", testEncodeDecodeOfClassInt64Unkeyed),
        ("testEncodeDecodeOfClassInt8Unkeyed", testEncodeDecodeOfClassInt8Unkeyed),
        ("testEncodeDecodeOfClassIntUnkeyed", testEncodeDecodeOfClassIntUnkeyed),
        ("testEncodeDecodeOfClassOptionalBoolUnkeyed", testEncodeDecodeOfClassOptionalBoolUnkeyed),
        ("testEncodeDecodeOfClassOptionalBoolWithNilUnkeyed", testEncodeDecodeOfClassOptionalBoolWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalCodableTypeUnkeyed", testEncodeDecodeOfClassOptionalCodableTypeUnkeyed),
        ("testEncodeDecodeOfClassOptionalCodableTypeWithNilUnkeyed", testEncodeDecodeOfClassOptionalCodableTypeWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalDoubleUnkeyed", testEncodeDecodeOfClassOptionalDoubleUnkeyed),
        ("testEncodeDecodeOfClassOptionalDoubleWithNilUnkeyed", testEncodeDecodeOfClassOptionalDoubleWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalFloatUnkeyed", testEncodeDecodeOfClassOptionalFloatUnkeyed),
        ("testEncodeDecodeOfClassOptionalFloatWithNilUnkeyed", testEncodeDecodeOfClassOptionalFloatWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalInt16Unkeyed", testEncodeDecodeOfClassOptionalInt16Unkeyed),
        ("testEncodeDecodeOfClassOptionalInt16WithNilUnkeyed", testEncodeDecodeOfClassOptionalInt16WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalInt32Unkeyed", testEncodeDecodeOfClassOptionalInt32Unkeyed),
        ("testEncodeDecodeOfClassOptionalInt32WithNilUnkeyed", testEncodeDecodeOfClassOptionalInt32WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalInt64Unkeyed", testEncodeDecodeOfClassOptionalInt64Unkeyed),
        ("testEncodeDecodeOfClassOptionalInt64WithNilUnkeyed", testEncodeDecodeOfClassOptionalInt64WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalInt8Unkeyed", testEncodeDecodeOfClassOptionalInt8Unkeyed),
        ("testEncodeDecodeOfClassOptionalInt8WithNilUnkeyed", testEncodeDecodeOfClassOptionalInt8WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalIntUnkeyed", testEncodeDecodeOfClassOptionalIntUnkeyed),
        ("testEncodeDecodeOfClassOptionalIntWithNilUnkeyed", testEncodeDecodeOfClassOptionalIntWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalStringUnkeyed", testEncodeDecodeOfClassOptionalStringUnkeyed),
        ("testEncodeDecodeOfClassOptionalStringWithNilUnkeyed", testEncodeDecodeOfClassOptionalStringWithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalUInt16Unkeyed", testEncodeDecodeOfClassOptionalUInt16Unkeyed),
        ("testEncodeDecodeOfClassOptionalUInt16WithNilUnkeyed", testEncodeDecodeOfClassOptionalUInt16WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalUInt32Unkeyed", testEncodeDecodeOfClassOptionalUInt32Unkeyed),
        ("testEncodeDecodeOfClassOptionalUInt32WithNilUnkeyed", testEncodeDecodeOfClassOptionalUInt32WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalUInt64Unkeyed", testEncodeDecodeOfClassOptionalUInt64Unkeyed),
        ("testEncodeDecodeOfClassOptionalUInt64WithNilUnkeyed", testEncodeDecodeOfClassOptionalUInt64WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalUInt8Unkeyed", testEncodeDecodeOfClassOptionalUInt8Unkeyed),
        ("testEncodeDecodeOfClassOptionalUInt8WithNilUnkeyed", testEncodeDecodeOfClassOptionalUInt8WithNilUnkeyed),
        ("testEncodeDecodeOfClassOptionalUIntUnkeyed", testEncodeDecodeOfClassOptionalUIntUnkeyed),
        ("testEncodeDecodeOfClassOptionalUIntWithNilUnkeyed", testEncodeDecodeOfClassOptionalUIntWithNilUnkeyed),
        ("testEncodeDecodeOfClassStringUnkeyed", testEncodeDecodeOfClassStringUnkeyed),
        ("testEncodeDecodeOfClassUInt16Unkeyed", testEncodeDecodeOfClassUInt16Unkeyed),
        ("testEncodeDecodeOfClassUInt32Unkeyed", testEncodeDecodeOfClassUInt32Unkeyed),
        ("testEncodeDecodeOfClassUInt64Unkeyed", testEncodeDecodeOfClassUInt64Unkeyed),
        ("testEncodeDecodeOfClassUInt8Unkeyed", testEncodeDecodeOfClassUInt8Unkeyed),
        ("testEncodeDecodeOfClassUIntUnkeyed", testEncodeDecodeOfClassUIntUnkeyed),
        ("testEncodeDecodeOfStructBoolUnkeyed", testEncodeDecodeOfStructBoolUnkeyed),
        ("testEncodeDecodeOfStructClassType", testEncodeDecodeOfStructClassType),
        ("testEncodeDecodeOfStructCodableTypeUnkeyed", testEncodeDecodeOfStructCodableTypeUnkeyed),
        ("testEncodeDecodeOfStructDoubleUnkeyed", testEncodeDecodeOfStructDoubleUnkeyed),
        ("testEncodeDecodeOfStructFloatUnkeyed", testEncodeDecodeOfStructFloatUnkeyed),
        ("testEncodeDecodeOfStructInt16Unkeyed", testEncodeDecodeOfStructInt16Unkeyed),
        ("testEncodeDecodeOfStructInt32Unkeyed", testEncodeDecodeOfStructInt32Unkeyed),
        ("testEncodeDecodeOfStructInt64Unkeyed", testEncodeDecodeOfStructInt64Unkeyed),
        ("testEncodeDecodeOfStructInt8Unkeyed", testEncodeDecodeOfStructInt8Unkeyed),
        ("testEncodeDecodeOfStructIntUnkeyed", testEncodeDecodeOfStructIntUnkeyed),
        ("testEncodeDecodeOfStructOptionalBoolUnkeyed", testEncodeDecodeOfStructOptionalBoolUnkeyed),
        ("testEncodeDecodeOfStructOptionalBoolWithNilUnkeyed", testEncodeDecodeOfStructOptionalBoolWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalCodableTypeUnkeyed", testEncodeDecodeOfStructOptionalCodableTypeUnkeyed),
        ("testEncodeDecodeOfStructOptionalCodableTypeWithNilUnkeyed", testEncodeDecodeOfStructOptionalCodableTypeWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalDoubleUnkeyed", testEncodeDecodeOfStructOptionalDoubleUnkeyed),
        ("testEncodeDecodeOfStructOptionalDoubleWithNilUnkeyed", testEncodeDecodeOfStructOptionalDoubleWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalFloatUnkeyed", testEncodeDecodeOfStructOptionalFloatUnkeyed),
        ("testEncodeDecodeOfStructOptionalFloatWithNilUnkeyed", testEncodeDecodeOfStructOptionalFloatWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalInt16Unkeyed", testEncodeDecodeOfStructOptionalInt16Unkeyed),
        ("testEncodeDecodeOfStructOptionalInt16WithNilUnkeyed", testEncodeDecodeOfStructOptionalInt16WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalInt32Unkeyed", testEncodeDecodeOfStructOptionalInt32Unkeyed),
        ("testEncodeDecodeOfStructOptionalInt32WithNilUnkeyed", testEncodeDecodeOfStructOptionalInt32WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalInt64Unkeyed", testEncodeDecodeOfStructOptionalInt64Unkeyed),
        ("testEncodeDecodeOfStructOptionalInt64WithNilUnkeyed", testEncodeDecodeOfStructOptionalInt64WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalInt8Unkeyed", testEncodeDecodeOfStructOptionalInt8Unkeyed),
        ("testEncodeDecodeOfStructOptionalInt8WithNilUnkeyed", testEncodeDecodeOfStructOptionalInt8WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalIntUnkeyed", testEncodeDecodeOfStructOptionalIntUnkeyed),
        ("testEncodeDecodeOfStructOptionalIntWithNilUnkeyed", testEncodeDecodeOfStructOptionalIntWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalStringUnkeyed", testEncodeDecodeOfStructOptionalStringUnkeyed),
        ("testEncodeDecodeOfStructOptionalStringWithNilUnkeyed", testEncodeDecodeOfStructOptionalStringWithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalUInt16Unkeyed", testEncodeDecodeOfStructOptionalUInt16Unkeyed),
        ("testEncodeDecodeOfStructOptionalUInt16WithNilUnkeyed", testEncodeDecodeOfStructOptionalUInt16WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalUInt32Unkeyed", testEncodeDecodeOfStructOptionalUInt32Unkeyed),
        ("testEncodeDecodeOfStructOptionalUInt32WithNilUnkeyed", testEncodeDecodeOfStructOptionalUInt32WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalUInt64Unkeyed", testEncodeDecodeOfStructOptionalUInt64Unkeyed),
        ("testEncodeDecodeOfStructOptionalUInt64WithNilUnkeyed", testEncodeDecodeOfStructOptionalUInt64WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalUInt8Unkeyed", testEncodeDecodeOfStructOptionalUInt8Unkeyed),
        ("testEncodeDecodeOfStructOptionalUInt8WithNilUnkeyed", testEncodeDecodeOfStructOptionalUInt8WithNilUnkeyed),
        ("testEncodeDecodeOfStructOptionalUIntUnkeyed", testEncodeDecodeOfStructOptionalUIntUnkeyed),
        ("testEncodeDecodeOfStructOptionalUIntWithNilUnkeyed", testEncodeDecodeOfStructOptionalUIntWithNilUnkeyed),
        ("testEncodeDecodeOfStructStringUnkeyed", testEncodeDecodeOfStructStringUnkeyed),
        ("testEncodeDecodeOfStructUInt16Unkeyed", testEncodeDecodeOfStructUInt16Unkeyed),
        ("testEncodeDecodeOfStructUInt32Unkeyed", testEncodeDecodeOfStructUInt32Unkeyed),
        ("testEncodeDecodeOfStructUInt64Unkeyed", testEncodeDecodeOfStructUInt64Unkeyed),
        ("testEncodeDecodeOfStructUInt8Unkeyed", testEncodeDecodeOfStructUInt8Unkeyed),
        ("testEncodeDecodeOfStructUIntUnkeyed", testEncodeDecodeOfStructUIntUnkeyed),
        ("testEncodeDecodeUnkeyedContainerCount", testEncodeDecodeUnkeyedContainerCount),
        ("testEncodeDecodeWithUnkeyedAndNestedKeyedContainers", testEncodeDecodeWithUnkeyedAndNestedKeyedContainers),
        ("testEncodeDecodeWithUnkeyedAndNestedUnkeyedContainer", testEncodeDecodeWithUnkeyedAndNestedUnkeyedContainer),
        ("testEncodeNilWithUnkeyedContainer", testEncodeNilWithUnkeyedContainer),
    ]
}

extension BinaryEncodingUserInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryEncodingUserInfoTests = [
        ("testUserInfoForDecoder", testUserInfoForDecoder),
        ("testUserInfoForKeyedContainer", testUserInfoForKeyedContainer),
        ("testUserInfoForKeyedNestedKeyedContainer", testUserInfoForKeyedNestedKeyedContainer),
        ("testUserInfoForKeyedNestedUnkeyedContainer", testUserInfoForKeyedNestedUnkeyedContainer),
        ("testUserInfoForUnkeyedContainer", testUserInfoForUnkeyedContainer),
        ("testUserInfoForUnkeyedNestedKeyedContainer", testUserInfoForUnkeyedNestedKeyedContainer),
        ("testUserInfoForUnkeyedNestedUnkeyedContainer", testUserInfoForUnkeyedNestedUnkeyedContainer),
    ]
}

extension DecodingError_ExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodingError_ExtensionsTests = [
        ("testKeyNotFoundError", testKeyNotFoundError),
        ("testTypeMismatchErrorForActuaTypeEncodedInt", testTypeMismatchErrorForActuaTypeEncodedInt),
        ("testTypeMismatchErrorForActuaTypeInt", testTypeMismatchErrorForActuaTypeInt),
        ("testTypeMismatchErrorForActuaTypeKeyedStorageContainer", testTypeMismatchErrorForActuaTypeKeyedStorageContainer),
        ("testTypeMismatchErrorForActuaTypeNullStorageContainer", testTypeMismatchErrorForActuaTypeNullStorageContainer),
        ("testTypeMismatchErrorForActuaTypeSingleValueContainer", testTypeMismatchErrorForActuaTypeSingleValueContainer),
        ("testTypeMismatchErrorForActuaTypeUnkeyedStorageContainer", testTypeMismatchErrorForActuaTypeUnkeyedStorageContainer),
        ("testValueNotFound", testValueNotFound),
        ("testValueNotFoundIsAtEnd", testValueNotFoundIsAtEnd),
    ]
}

extension DocumentationExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentationExampleTests = [
        ("testArrayConstructionExample", testArrayConstructionExample),
        ("testBinaryDecoderExample1", testBinaryDecoderExample1),
        ("testBinaryEncoderExample1", testBinaryEncoderExample1),
        ("testBinaryEncoderExample2", testBinaryEncoderExample2),
        ("testDataConstructionExample", testDataConstructionExample),
        ("testEncodedDataExample1", testEncodedDataExample1),
        ("testEncodedDataExample2", testEncodedDataExample2),
    ]
}

extension EncodedDataNegativeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodedDataNegativeTests = [
        ("testNonSupportedFirstByte", testNonSupportedFirstByte),
    ]
}

extension EncodedDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodedDataTests = [
        ("testArrayFullRoundTripOfBasicStruct", testArrayFullRoundTripOfBasicStruct),
        ("testArrayRoundTripOfSingleValueContainer", testArrayRoundTripOfSingleValueContainer),
        ("testBytesRoundTripOfKeyedStorageContainer", testBytesRoundTripOfKeyedStorageContainer),
        ("testBytesRoundTripOfNullStorageContainer", testBytesRoundTripOfNullStorageContainer),
        ("testBytesRoundTripOfSingleValueContainer", testBytesRoundTripOfSingleValueContainer),
        ("testBytesRoundTripOfUnkeyedStorageContainer", testBytesRoundTripOfUnkeyedStorageContainer),
        ("testDataFullRoundTripOfBasicStruct", testDataFullRoundTripOfBasicStruct),
        ("testDataRoundTripOfSingleValueContainer", testDataRoundTripOfSingleValueContainer),
        ("testInit", testInit),
        ("testUnsafeRawBufferPointerFullRoundTripOfBasicStruct", testUnsafeRawBufferPointerFullRoundTripOfBasicStruct),
        ("testUnsafeRawBufferPointerRoundTripOfKeyedStorageContainer", testUnsafeRawBufferPointerRoundTripOfKeyedStorageContainer),
        ("testUnsafeRawBufferPointerRoundTripOfNullStorageContainer", testUnsafeRawBufferPointerRoundTripOfNullStorageContainer),
        ("testUnsafeRawBufferPointerRoundTripOfSingleValueContainer", testUnsafeRawBufferPointerRoundTripOfSingleValueContainer),
        ("testUnsafeRawBufferPointerRoundTripOfUnkeyedStorageContainer", testUnsafeRawBufferPointerRoundTripOfUnkeyedStorageContainer),
    ]
}

extension EncodedTypePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodedTypePerformanceTests = [
        ("testEncodedTypeForBoolPerformance", testEncodedTypeForBoolPerformance),
        ("testEncodedTypeForDoublePerformance", testEncodedTypeForDoublePerformance),
        ("testEncodedTypeForFloatPerformance", testEncodedTypeForFloatPerformance),
        ("testEncodedTypeForInt16Performance", testEncodedTypeForInt16Performance),
        ("testEncodedTypeForInt32Performance", testEncodedTypeForInt32Performance),
        ("testEncodedTypeForInt64Performance", testEncodedTypeForInt64Performance),
        ("testEncodedTypeForInt8Performance", testEncodedTypeForInt8Performance),
        ("testEncodedTypeForIntPerformance", testEncodedTypeForIntPerformance),
        ("testEncodedTypeForStringPerformance", testEncodedTypeForStringPerformance),
        ("testEncodedTypeForUInt16Performance", testEncodedTypeForUInt16Performance),
        ("testEncodedTypeForUInt32Performance", testEncodedTypeForUInt32Performance),
        ("testEncodedTypeForUInt64Performance", testEncodedTypeForUInt64Performance),
        ("testEncodedTypeForUInt8Performance", testEncodedTypeForUInt8Performance),
        ("testEncodedTypeForUIntPerformance", testEncodedTypeForUIntPerformance),
    ]
}

extension EncodedTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodedTypeTests = [
        ("testDebugDescriptionForBool", testDebugDescriptionForBool),
        ("testDebugDescriptionForDouble", testDebugDescriptionForDouble),
        ("testDebugDescriptionForFloat", testDebugDescriptionForFloat),
        ("testDebugDescriptionForInt", testDebugDescriptionForInt),
        ("testDebugDescriptionForInt16", testDebugDescriptionForInt16),
        ("testDebugDescriptionForInt32", testDebugDescriptionForInt32),
        ("testDebugDescriptionForInt64", testDebugDescriptionForInt64),
        ("testDebugDescriptionForInt8", testDebugDescriptionForInt8),
        ("testDebugDescriptionForString", testDebugDescriptionForString),
        ("testDebugDescriptionForUInt", testDebugDescriptionForUInt),
        ("testDebugDescriptionForUInt16", testDebugDescriptionForUInt16),
        ("testDebugDescriptionForUInt32", testDebugDescriptionForUInt32),
        ("testDebugDescriptionForUInt64", testDebugDescriptionForUInt64),
        ("testDebugDescriptionForUInt8", testDebugDescriptionForUInt8),
        ("testDebugDescriptionForUnknownType", testDebugDescriptionForUnknownType),
        ("testDescriptionForBool", testDescriptionForBool),
        ("testDescriptionForDouble", testDescriptionForDouble),
        ("testDescriptionForFloat", testDescriptionForFloat),
        ("testDescriptionForInt", testDescriptionForInt),
        ("testDescriptionForInt16", testDescriptionForInt16),
        ("testDescriptionForInt32", testDescriptionForInt32),
        ("testDescriptionForInt64", testDescriptionForInt64),
        ("testDescriptionForInt8", testDescriptionForInt8),
        ("testDescriptionForString", testDescriptionForString),
        ("testDescriptionForUInt", testDescriptionForUInt),
        ("testDescriptionForUInt16", testDescriptionForUInt16),
        ("testDescriptionForUInt32", testDescriptionForUInt32),
        ("testDescriptionForUInt64", testDescriptionForUInt64),
        ("testDescriptionForUInt8", testDescriptionForUInt8),
        ("testDescriptionForUnknownType", testDescriptionForUnknownType),
        ("testEncodedTypeForBool", testEncodedTypeForBool),
        ("testEncodedTypeForDouble", testEncodedTypeForDouble),
        ("testEncodedTypeForFloat", testEncodedTypeForFloat),
        ("testEncodedTypeForInt", testEncodedTypeForInt),
        ("testEncodedTypeForInt16", testEncodedTypeForInt16),
        ("testEncodedTypeForInt32", testEncodedTypeForInt32),
        ("testEncodedTypeForInt64", testEncodedTypeForInt64),
        ("testEncodedTypeForInt8", testEncodedTypeForInt8),
        ("testEncodedTypeForString", testEncodedTypeForString),
        ("testEncodedTypeForUInt", testEncodedTypeForUInt),
        ("testEncodedTypeForUInt16", testEncodedTypeForUInt16),
        ("testEncodedTypeForUInt32", testEncodedTypeForUInt32),
        ("testEncodedTypeForUInt64", testEncodedTypeForUInt64),
        ("testEncodedTypeForUInt8", testEncodedTypeForUInt8),
    ]
}

extension KeyedStorageContainerElementReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedStorageContainerElementReferenceTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithValue", testDebugDescriptionWithValue),
        ("testDescription", testDescription),
        ("testDescriptionWithValue", testDescriptionWithValue),
        ("testInit", testInit),
    ]
}

extension KeyedStorageContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedStorageContainerTests = [
        ("testContains", testContains),
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithValues", testDebugDescriptionWithValues),
        ("testDescription", testDescription),
        ("testDescriptionWithValues", testDescriptionWithValues),
        ("testInit", testInit),
        ("testKeys", testKeys),
        ("testSubscript", testSubscript),
    ]
}

extension NullStorageContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NullStorageContainerTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDescription", testDescription),
        ("testNull", testNull),
        ("testNullIsTheSameObject", testNullIsTheSameObject),
    ]
}

extension PassthroughReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PassthroughReferenceTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithWrappedValue", testDebugDescriptionWithWrappedValue),
        ("testDescription", testDescription),
        ("testDescriptionWithWrappedValue", testDescriptionWithWrappedValue),
        ("testInit", testInit),
        ("testInitWithValue", testInitWithValue),
    ]
}

extension SingleValueContainerPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SingleValueContainerPerformanceTests = [
        ("testInitWithBoolPerformance", testInitWithBoolPerformance),
        ("testInitWithDoublePerformance", testInitWithDoublePerformance),
        ("testInitWithFloatPerformance", testInitWithFloatPerformance),
        ("testInitWithInt16Performance", testInitWithInt16Performance),
        ("testInitWithInt32Performance", testInitWithInt32Performance),
        ("testInitWithInt64Performance", testInitWithInt64Performance),
        ("testInitWithInt8Performance", testInitWithInt8Performance),
        ("testInitWithIntPerformance", testInitWithIntPerformance),
        ("testInitWithLargeRandomString1000kPerformance", testInitWithLargeRandomString1000kPerformance),
        ("testInitWithLargeRandomString100kPerformance", testInitWithLargeRandomString100kPerformance),
        ("testInitWithStringPerformance", testInitWithStringPerformance),
        ("testInitWithUInt16Performance", testInitWithUInt16Performance),
        ("testInitWithUInt32Performance", testInitWithUInt32Performance),
        ("testInitWithUInt64Performance", testInitWithUInt64Performance),
        ("testInitWithUInt8Performance", testInitWithUInt8Performance),
        ("testInitWithUIntPerformance", testInitWithUIntPerformance),
        ("testSizeWithBoolPerformance", testSizeWithBoolPerformance),
        ("testSizeWithDoublePerformance", testSizeWithDoublePerformance),
        ("testSizeWithFloatPerformance", testSizeWithFloatPerformance),
        ("testSizeWithInt16Performance", testSizeWithInt16Performance),
        ("testSizeWithInt32Performance", testSizeWithInt32Performance),
        ("testSizeWithInt64Performance", testSizeWithInt64Performance),
        ("testSizeWithInt8Performance", testSizeWithInt8Performance),
        ("testSizeWithIntPerformance", testSizeWithIntPerformance),
        ("testSizeWithStringPerformance", testSizeWithStringPerformance),
        ("testSizeWithUInt16Performance", testSizeWithUInt16Performance),
        ("testSizeWithUInt32Performance", testSizeWithUInt32Performance),
        ("testSizeWithUInt64Performance", testSizeWithUInt64Performance),
        ("testSizeWithUInt8Performance", testSizeWithUInt8Performance),
        ("testSizeWithUIntPerformance", testSizeWithUIntPerformance),
        ("testTypeWithBoolPerformance", testTypeWithBoolPerformance),
        ("testTypeWithDoublePerformance", testTypeWithDoublePerformance),
        ("testTypeWithFloatPerformance", testTypeWithFloatPerformance),
        ("testTypeWithInt16Performance", testTypeWithInt16Performance),
        ("testTypeWithInt32Performance", testTypeWithInt32Performance),
        ("testTypeWithInt64Performance", testTypeWithInt64Performance),
        ("testTypeWithInt8Performance", testTypeWithInt8Performance),
        ("testTypeWithIntPerformance", testTypeWithIntPerformance),
        ("testTypeWithStringPerformance", testTypeWithStringPerformance),
        ("testTypeWithUInt16Performance", testTypeWithUInt16Performance),
        ("testTypeWithUInt32Performance", testTypeWithUInt32Performance),
        ("testTypeWithUInt64Performance", testTypeWithUInt64Performance),
        ("testTypeWithUInt8Performance", testTypeWithUInt8Performance),
        ("testTypeWithUIntPerformance", testTypeWithUIntPerformance),
        ("testValueWithBoolPerformance", testValueWithBoolPerformance),
        ("testValueWithDoublePerformance", testValueWithDoublePerformance),
        ("testValueWithFloatPerformance", testValueWithFloatPerformance),
        ("testValueWithInt16Performance", testValueWithInt16Performance),
        ("testValueWithInt32Performance", testValueWithInt32Performance),
        ("testValueWithInt64Performance", testValueWithInt64Performance),
        ("testValueWithInt8Performance", testValueWithInt8Performance),
        ("testValueWithIntPerformance", testValueWithIntPerformance),
        ("testValueWithLargeRandomString1000kPerformance", testValueWithLargeRandomString1000kPerformance),
        ("testValueWithLargeRandomString100kPerformance", testValueWithLargeRandomString100kPerformance),
        ("testValueWithStringPerformance", testValueWithStringPerformance),
        ("testValueWithUInt16Performance", testValueWithUInt16Performance),
        ("testValueWithUInt32Performance", testValueWithUInt32Performance),
        ("testValueWithUInt64Performance", testValueWithUInt64Performance),
        ("testValueWithUInt8Performance", testValueWithUInt8Performance),
        ("testValueWithUIntPerformance", testValueWithUIntPerformance),
    ]
}

extension SingleValueContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SingleValueContainerTests = [
        ("testCanStoreDoubleInfinity", testCanStoreDoubleInfinity),
        ("testCanStoreDoubleNan", testCanStoreDoubleNan),
        ("testCanStoreFloatInfinity", testCanStoreFloatInfinity),
        ("testCanStoreFloatNan", testCanStoreFloatNan),
        ("testCanStoreInt16Max", testCanStoreInt16Max),
        ("testCanStoreInt16Min", testCanStoreInt16Min),
        ("testCanStoreInt32Max", testCanStoreInt32Max),
        ("testCanStoreInt32Min", testCanStoreInt32Min),
        ("testCanStoreInt64Max", testCanStoreInt64Max),
        ("testCanStoreInt64Min", testCanStoreInt64Min),
        ("testCanStoreInt8Max", testCanStoreInt8Max),
        ("testCanStoreInt8Min", testCanStoreInt8Min),
        ("testCanStoreIntMax", testCanStoreIntMax),
        ("testCanStoreIntMin", testCanStoreIntMin),
        ("testCanStoreLargeRandomString1000k", testCanStoreLargeRandomString1000k),
        ("testCanStoreLargeRandomString100k", testCanStoreLargeRandomString100k),
        ("testCanStoreStringUnicodeEPlusAccent", testCanStoreStringUnicodeEPlusAccent),
        ("testCanStoreStringUnicodeEWithAccent", testCanStoreStringUnicodeEWithAccent),
        ("testCanStoreStringUnicodeFlags", testCanStoreStringUnicodeFlags),
        ("testCanStoreStringUnicodeGlobes", testCanStoreStringUnicodeGlobes),
        ("testCanStoreUInt16Max", testCanStoreUInt16Max),
        ("testCanStoreUInt16Min", testCanStoreUInt16Min),
        ("testCanStoreUInt32Max", testCanStoreUInt32Max),
        ("testCanStoreUInt32Min", testCanStoreUInt32Min),
        ("testCanStoreUInt64Max", testCanStoreUInt64Max),
        ("testCanStoreUInt64Min", testCanStoreUInt64Min),
        ("testCanStoreUInt8Max", testCanStoreUInt8Max),
        ("testCanStoreUInt8Min", testCanStoreUInt8Min),
        ("testCanStoreUIntMax", testCanStoreUIntMax),
        ("testCanStoreUIntMin", testCanStoreUIntMin),
        ("testDebugDescriptionWithBool", testDebugDescriptionWithBool),
        ("testDebugDescriptionWithDouble", testDebugDescriptionWithDouble),
        ("testDebugDescriptionWithFloat", testDebugDescriptionWithFloat),
        ("testDebugDescriptionWithInt16", testDebugDescriptionWithInt16),
        ("testDebugDescriptionWithInt32", testDebugDescriptionWithInt32),
        ("testDebugDescriptionWithInt64", testDebugDescriptionWithInt64),
        ("testDebugDescriptionWithInt8", testDebugDescriptionWithInt8),
        ("testDebugDescriptionWithInt", testDebugDescriptionWithInt),
        ("testDebugDescriptionWithString", testDebugDescriptionWithString),
        ("testDebugDescriptionWithUInt16", testDebugDescriptionWithUInt16),
        ("testDebugDescriptionWithUInt32", testDebugDescriptionWithUInt32),
        ("testDebugDescriptionWithUInt64", testDebugDescriptionWithUInt64),
        ("testDebugDescriptionWithUInt8", testDebugDescriptionWithUInt8),
        ("testDebugDescriptionWithUInt", testDebugDescriptionWithUInt),
        ("testDescriptionWithBool", testDescriptionWithBool),
        ("testDescriptionWithDouble", testDescriptionWithDouble),
        ("testDescriptionWithFloat", testDescriptionWithFloat),
        ("testDescriptionWithInt16", testDescriptionWithInt16),
        ("testDescriptionWithInt32", testDescriptionWithInt32),
        ("testDescriptionWithInt64", testDescriptionWithInt64),
        ("testDescriptionWithInt8", testDescriptionWithInt8),
        ("testDescriptionWithInt", testDescriptionWithInt),
        ("testDescriptionWithString", testDescriptionWithString),
        ("testDescriptionWithUInt16", testDescriptionWithUInt16),
        ("testDescriptionWithUInt32", testDescriptionWithUInt32),
        ("testDescriptionWithUInt64", testDescriptionWithUInt64),
        ("testDescriptionWithUInt8", testDescriptionWithUInt8),
        ("testDescriptionWithUInt", testDescriptionWithUInt),
        ("testInitWithBool", testInitWithBool),
        ("testInitWithDouble", testInitWithDouble),
        ("testInitWithFloat", testInitWithFloat),
        ("testInitWithInt", testInitWithInt),
        ("testInitWithInt16", testInitWithInt16),
        ("testInitWithInt32", testInitWithInt32),
        ("testInitWithInt64", testInitWithInt64),
        ("testInitWithInt8", testInitWithInt8),
        ("testInitWithString", testInitWithString),
        ("testInitWithUInt", testInitWithUInt),
        ("testInitWithUInt16", testInitWithUInt16),
        ("testInitWithUInt32", testInitWithUInt32),
        ("testInitWithUInt64", testInitWithUInt64),
        ("testInitWithUInt8", testInitWithUInt8),
        ("testSizeWithBool", testSizeWithBool),
        ("testSizeWithDouble", testSizeWithDouble),
        ("testSizeWithFloat", testSizeWithFloat),
        ("testSizeWithInt", testSizeWithInt),
        ("testSizeWithInt16", testSizeWithInt16),
        ("testSizeWithInt32", testSizeWithInt32),
        ("testSizeWithInt64", testSizeWithInt64),
        ("testSizeWithInt8", testSizeWithInt8),
        ("testSizeWithString", testSizeWithString),
        ("testSizeWithUInt", testSizeWithUInt),
        ("testSizeWithUInt16", testSizeWithUInt16),
        ("testSizeWithUInt32", testSizeWithUInt32),
        ("testSizeWithUInt64", testSizeWithUInt64),
        ("testSizeWithUInt8", testSizeWithUInt8),
        ("testTypeWithBool", testTypeWithBool),
        ("testTypeWithDouble", testTypeWithDouble),
        ("testTypeWithFloat", testTypeWithFloat),
        ("testTypeWithInt", testTypeWithInt),
        ("testTypeWithInt16", testTypeWithInt16),
        ("testTypeWithInt32", testTypeWithInt32),
        ("testTypeWithInt64", testTypeWithInt64),
        ("testTypeWithInt8", testTypeWithInt8),
        ("testTypeWithString", testTypeWithString),
        ("testTypeWithUInt", testTypeWithUInt),
        ("testTypeWithUInt16", testTypeWithUInt16),
        ("testTypeWithUInt32", testTypeWithUInt32),
        ("testTypeWithUInt64", testTypeWithUInt64),
        ("testTypeWithUInt8", testTypeWithUInt8),
        ("testUnsafeMutableRawBufferPointerRoundTripOfBool", testUnsafeMutableRawBufferPointerRoundTripOfBool),
        ("testUnsafeMutableRawBufferPointerRoundTripOfDouble", testUnsafeMutableRawBufferPointerRoundTripOfDouble),
        ("testUnsafeMutableRawBufferPointerRoundTripOfFloat", testUnsafeMutableRawBufferPointerRoundTripOfFloat),
        ("testUnsafeMutableRawBufferPointerRoundTripOfInt16", testUnsafeMutableRawBufferPointerRoundTripOfInt16),
        ("testUnsafeMutableRawBufferPointerRoundTripOfInt32", testUnsafeMutableRawBufferPointerRoundTripOfInt32),
        ("testUnsafeMutableRawBufferPointerRoundTripOfInt64", testUnsafeMutableRawBufferPointerRoundTripOfInt64),
        ("testUnsafeMutableRawBufferPointerRoundTripOfInt8", testUnsafeMutableRawBufferPointerRoundTripOfInt8),
        ("testUnsafeMutableRawBufferPointerRoundTripOfInt", testUnsafeMutableRawBufferPointerRoundTripOfInt),
        ("testUnsafeMutableRawBufferPointerRoundTripOfString", testUnsafeMutableRawBufferPointerRoundTripOfString),
        ("testUnsafeMutableRawBufferPointerRoundTripOfUInt16", testUnsafeMutableRawBufferPointerRoundTripOfUInt16),
        ("testUnsafeMutableRawBufferPointerRoundTripOfUInt32", testUnsafeMutableRawBufferPointerRoundTripOfUInt32),
        ("testUnsafeMutableRawBufferPointerRoundTripOfUInt64", testUnsafeMutableRawBufferPointerRoundTripOfUInt64),
        ("testUnsafeMutableRawBufferPointerRoundTripOfUInt8", testUnsafeMutableRawBufferPointerRoundTripOfUInt8),
        ("testUnsafeMutableRawBufferPointerRoundTripOfUInt", testUnsafeMutableRawBufferPointerRoundTripOfUInt),
        ("testValueWithBool", testValueWithBool),
        ("testValueWithDouble", testValueWithDouble),
        ("testValueWithFloat", testValueWithFloat),
        ("testValueWithInt16", testValueWithInt16),
        ("testValueWithInt32", testValueWithInt32),
        ("testValueWithInt64", testValueWithInt64),
        ("testValueWithInt8", testValueWithInt8),
        ("testValueWithInt", testValueWithInt),
        ("testValueWithString", testValueWithString),
        ("testValueWithUInt16", testValueWithUInt16),
        ("testValueWithUInt32", testValueWithUInt32),
        ("testValueWithUInt64", testValueWithUInt64),
        ("testValueWithUInt8", testValueWithUInt8),
        ("testValueWithUInt", testValueWithUInt),
    ]
}

extension StorageContainerEqualTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageContainerEqualTests = [
        ("testEqualWithKeyedStorageContainer", testEqualWithKeyedStorageContainer),
        ("testEqualWithKeyedStorageContainerAndNestedSingleValueeContainer", testEqualWithKeyedStorageContainerAndNestedSingleValueeContainer),
        ("testEqualWithNullStorageContainer", testEqualWithNullStorageContainer),
        ("testEqualWithSingleValueContainer", testEqualWithSingleValueContainer),
        ("testEqualWithUnkeyedStorageContainer", testEqualWithUnkeyedStorageContainer),
        ("testEqualWithUnkeyedStorageContainerAndNestedSingleValueeContainer", testEqualWithUnkeyedStorageContainerAndNestedSingleValueeContainer),
        ("testNotEqualWithKeyedStorageContainer", testNotEqualWithKeyedStorageContainer),
        ("testNotEqualWithKeyedStorageContainerAndNestedSingleValueContainer", testNotEqualWithKeyedStorageContainerAndNestedSingleValueContainer),
        ("testNotEqualWithNullStorageContainer", testNotEqualWithNullStorageContainer),
        ("testNotEqualWithSingleValueContainer", testNotEqualWithSingleValueContainer),
        ("testNotEqualWithUnkeyedStorageContainer", testNotEqualWithUnkeyedStorageContainer),
        ("testNotEqualWithUnkeyedStorageContainerAndNestedSingleValueContainer", testNotEqualWithUnkeyedStorageContainerAndNestedSingleValueContainer),
    ]
}

extension StorageContainerReaderWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageContainerReaderWriterTests = [
        ("testReadWriteRoundTripForKeyedContainer", testReadWriteRoundTripForKeyedContainer),
        ("testReadWriteRoundTripForNullStorageContainer", testReadWriteRoundTripForNullStorageContainer),
        ("testReadWriteRoundTripForSingleValueContainer", testReadWriteRoundTripForSingleValueContainer),
        ("testReadWriteRoundTripForUnkeyedContainer", testReadWriteRoundTripForUnkeyedContainer),
        ("testReadWriteRoundTripForUnkeyedContainerWithMixedSingleValueAndNull", testReadWriteRoundTripForUnkeyedContainerWithMixedSingleValueAndNull),
        ("testReadWriteRoundTripForUnkeyedContainerWithNestedUnkeyedContainers", testReadWriteRoundTripForUnkeyedContainerWithNestedUnkeyedContainers),
    ]
}

extension StorageContainerReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageContainerReferenceTests = [
        ("testCanImplement", testCanImplement),
    ]
}

extension StorageContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageContainerTests = [
        ("testCanImplement", testCanImplement),
    ]
}

extension UnkeyedStorageContainerElementReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedStorageContainerElementReferenceTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithValue", testDebugDescriptionWithValue),
        ("testDescription", testDescription),
        ("testDescriptionWithValue", testDescriptionWithValue),
        ("testInit", testInit),
        ("testValueGet", testValueGet),
        ("testValueSet", testValueSet),
    ]
}

extension UnkeyedStorageContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedStorageContainerTests = [
        ("testDebugDescription", testDebugDescription),
        ("testDebugDescriptionWithValues", testDebugDescriptionWithValues),
        ("testDescription", testDescription),
        ("testDescriptionWithValues", testDescriptionWithValues),
        ("testInit", testInit),
        ("testPush", testPush),
        ("testSubscript", testSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryCodingKeyTests.__allTests__BinaryCodingKeyTests),
        testCase(BinaryDecoderNegativeTests.__allTests__BinaryDecoderNegativeTests),
        testCase(BinaryEncoderUserObjectNegativeTests.__allTests__BinaryEncoderUserObjectNegativeTests),
        testCase(BinaryEncodingKeyedContainerNegativeTests.__allTests__BinaryEncodingKeyedContainerNegativeTests),
        testCase(BinaryEncodingKeyedContainerTests.__allTests__BinaryEncodingKeyedContainerTests),
        testCase(BinaryEncodingSingleValueContainerNegativeTests.__allTests__BinaryEncodingSingleValueContainerNegativeTests),
        testCase(BinaryEncodingSingleValueContainerTests.__allTests__BinaryEncodingSingleValueContainerTests),
        testCase(BinaryEncodingStructuredTypeTests.__allTests__BinaryEncodingStructuredTypeTests),
        testCase(BinaryEncodingUnkeyedContainerNegativeTests.__allTests__BinaryEncodingUnkeyedContainerNegativeTests),
        testCase(BinaryEncodingUnkeyedContainerTests.__allTests__BinaryEncodingUnkeyedContainerTests),
        testCase(BinaryEncodingUserInfoTests.__allTests__BinaryEncodingUserInfoTests),
        testCase(DecodingError_ExtensionsTests.__allTests__DecodingError_ExtensionsTests),
        testCase(DocumentationExampleTests.__allTests__DocumentationExampleTests),
        testCase(EncodedDataNegativeTests.__allTests__EncodedDataNegativeTests),
        testCase(EncodedDataTests.__allTests__EncodedDataTests),
        testCase(EncodedTypePerformanceTests.__allTests__EncodedTypePerformanceTests),
        testCase(EncodedTypeTests.__allTests__EncodedTypeTests),
        testCase(KeyedStorageContainerElementReferenceTests.__allTests__KeyedStorageContainerElementReferenceTests),
        testCase(KeyedStorageContainerTests.__allTests__KeyedStorageContainerTests),
        testCase(NullStorageContainerTests.__allTests__NullStorageContainerTests),
        testCase(PassthroughReferenceTests.__allTests__PassthroughReferenceTests),
        testCase(SingleValueContainerPerformanceTests.__allTests__SingleValueContainerPerformanceTests),
        testCase(SingleValueContainerTests.__allTests__SingleValueContainerTests),
        testCase(StorageContainerEqualTests.__allTests__StorageContainerEqualTests),
        testCase(StorageContainerReaderWriterTests.__allTests__StorageContainerReaderWriterTests),
        testCase(StorageContainerReferenceTests.__allTests__StorageContainerReferenceTests),
        testCase(StorageContainerTests.__allTests__StorageContainerTests),
        testCase(UnkeyedStorageContainerElementReferenceTests.__allTests__UnkeyedStorageContainerElementReferenceTests),
        testCase(UnkeyedStorageContainerTests.__allTests__UnkeyedStorageContainerTests),
    ]
}
#endif
